### PR TITLE
Add various attributes to _LOCAL_METHODS to not waste bridge calls

### PR DESCRIPTION
**Pull request by fmagin**
This replaces #33 by just making sure that the local object handles those attributes/properties. There shouldn't be any exceptions in the server log anymore when using `currentProgram?` or similiar.

I moved my IPython and Ghidra specific features to [ipyghidra](https://github.com/fmagin/ipyghidra) which is a IPython extension that implements all the features I had hacked together without having to hack them into the actual `ghidra_bridge` code.

### CODE REVIEW

**Comment by justfoxing** [comment]
ipyghidra looks great! I think that definitely sounds like a good way forward for the ipython specific ideas.

I'll merge this, but I'm going to take __doc__ back out of that list. I've got my own use cases for being able to access that remotely that this would break. It will cause some server side complaining when ? is used in ipython, but that doesn't actually break anything - I'll try to take a look at that in future.

**Comment by fmagin** [comment]
I think I can just change that to `.getdoc()` which IPython checks first. What are you trying to do with __doc__ ?

For now ipyghidra does some fairly horrible monkey patching https://github.com/fmagin/ipyghidra/blob/master/ipyghidra/doc_helper.py#L153-L157 so maybe some standardized interface to defer those methods to some extra class would be nice.

**Comment by justfoxing** [comment]
Also rearranged to drop most of them into the DONT_BRIDGE_UNLESS_IN_ATTRS list, instead of LOCAL_METHODS, because most of them are actually attributes.

**Comment by fmagin** [comment]
But I implemented them as properties and I think that was requiring them to be in LOCAL_METHODS. Now I am getting AttributeErrors when accessing e.g. __signature__ because `attr in BridgedObject._DONT_BRIDGE_UNLESS_IN_ATTRS and attr not in self._bridge_attrs` is true. Maybe I have to also add them to `_bridge_attrs` but I would have to do that for every object for which I can't think of a good method right now

**Comment by fmagin** [comment]
Is that just a bug? Attributes in `_DONT_BRIDGE_UNLESS_IN_ATTRS` seem like they can never return anything besides the result of remote_get. I am not sure what that check in https://github.com/justfoxing/ghidra_bridge/blob/5d528e6f90f93403836731fde293b1300be5c3ed/ghidra_bridge/bridge.py#L1070 is even accomplishing at all. My intuition would be that all those checks should be extra `or` clauses for the check above

**Pull request merged**
